GET http://localhost:3000/pruebas


### 
GET http://localhost:3000/products
###
PUT http://localhost:3000/products/edit

###
POST http://localhost:3000/users/create
Content-Type: application/json

{
    "username": "mairi",
    "password": "1234",
    "age": 33,
    "email": "mairi@mairi"

}

###
GET http://localhost:3000/users/active

###
DELETE http://localhost:3000/users/delete

###
GET http://localhost:3000/products/department/moda
###
GET http://localhost:3000/products/department/oficina

###
GET http://localhost:3000/products/department/cocina

### 

GET http://localhost:3000/users/23/comments/378

########
### API ####
#########
GET http://localhost:3000/api/users


###
POST http://localhost:3000/api/users

###
PUT http://localhost:3000/api/users/123

###
DELETE http://localhost:3000/api/users/1234



